# Generated by Django 5.1.7 on 2025-04-09 16:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DefDocumentos',
            fields=[
                ('documento_id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DefStatusSolicitacoes',
            fields=[
                ('status_solicitacao_id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitacoes',
            fields=[
                ('solicitacao_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('ambiente', models.CharField(max_length=200)),
                ('certificado', models.BooleanField(default=False)),
                ('data_inicial', models.DateField()),
                ('data_final', models.DateField()),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True)),
                ('documento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.defdocumentos')),
                ('status_solicitacao_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.defstatussolicitacoes')),
            ],
        ),
    ]
