# Generated by Django 5.1.7 on 2025-04-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacoes',
            name='cnpj',
            field=models.CharField(max_length=14),
        ),
    ]
